/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetsCarbonaiRouteImport } from './routes/projets.carbonai'
import { Route as ProjetsOptisenseRouteImport } from './routes/projets.optisense'
import { Route as ProjetsPipelineDonneesWebRouteImport } from './routes/projets.pipeline-donnees-web'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsCarbonaiRoute = ProjetsCarbonaiRouteImport.update({
  id: '/projets/carbonai',
  path: '/projets/carbonai',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsOptisenseRoute = ProjetsOptisenseRouteImport.update({
  id: '/projets/optisense',
  path: '/projets/optisense',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsPipelineDonneesWebRoute =
  ProjetsPipelineDonneesWebRouteImport.update({
    id: '/projets/pipeline-donnees-web',
    path: '/projets/pipeline-donnees-web',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projets/carbonai': typeof ProjetsCarbonaiRoute
  '/projets/optisense': typeof ProjetsOptisenseRoute
  '/projets/pipeline-donnees-web': typeof ProjetsPipelineDonneesWebRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projets/carbonai': typeof ProjetsCarbonaiRoute
  '/projets/optisense': typeof ProjetsOptisenseRoute
  '/projets/pipeline-donnees-web': typeof ProjetsPipelineDonneesWebRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projets/carbonai': typeof ProjetsCarbonaiRoute
  '/projets/optisense': typeof ProjetsOptisenseRoute
  '/projets/pipeline-donnees-web': typeof ProjetsPipelineDonneesWebRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projets/carbonai'
    | '/projets/optisense'
    | '/projets/pipeline-donnees-web'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projets/carbonai'
    | '/projets/optisense'
    | '/projets/pipeline-donnees-web'
  id:
    | '__root__'
    | '/'
    | '/projets/carbonai'
    | '/projets/optisense'
    | '/projets/pipeline-donnees-web'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjetsCarbonaiRoute: typeof ProjetsCarbonaiRoute
  ProjetsOptisenseRoute: typeof ProjetsOptisenseRoute
  ProjetsPipelineDonneesWebRoute: typeof ProjetsPipelineDonneesWebRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/carbonai': {
      id: '/projets/carbonai'
      path: '/projets/carbonai'
      fullPath: '/projets/carbonai'
      preLoaderRoute: typeof ProjetsCarbonaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/optisense': {
      id: '/projets/optisense'
      path: '/projets/optisense'
      fullPath: '/projets/optisense'
      preLoaderRoute: typeof ProjetsOptisenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/pipeline-donnees-web': {
      id: '/projets/pipeline-donnees-web'
      path: '/projets/pipeline-donnees-web'
      fullPath: '/projets/pipeline-donnees-web'
      preLoaderRoute: typeof ProjetsPipelineDonneesWebRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjetsCarbonaiRoute: ProjetsCarbonaiRoute,
  ProjetsOptisenseRoute: ProjetsOptisenseRoute,
  ProjetsPipelineDonneesWebRoute: ProjetsPipelineDonneesWebRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
